---
galaxy_info:
  role_name: telegram_notification
  author: danjam
  description: Role for sending Telegram notifications from Ansible
  license: GPL-3.0-or-later
  min_ansible_version: 2.10
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: GenericUNIX
      versions:
        - all
  galaxy_tags:
    - telegram
    - notification
    - messaging
    - alert

dependencies: []