---
- name: Start Docker containers
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_project_dir }}"
    files: "{{ docker_compose_file }}"
    state: present
    remove_orphans: yes
    pull: always
  tags:
    - deploy

- name: Remove unused Docker resources
  community.docker.docker_prune:
    containers: yes
    images: yes
    networks: yes
    volumes: yes
    builder_cache: yes
    images_filters:
      dangling: false

# - name: Prune Docker images
#   ansible.builtin.command: docker image prune -af
#   tags:
#     - cleanup
#     - prune

# - name: Prune Docker volumes
#   ansible.builtin.command: docker volume prune -f
#   tags:
#     - cleanup
#     - prune

# - name: Prune Docker system
#   ansible.builtin.command: docker system prune -f
#   tags:
#     - cleanup
#     - prune